language: android
sudo: false
android:
  components:
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-android-support
    - extra-android-m2repository
jdk:
  - oraclejdk8
before_install:
  - chmod +x ./gradlew
script: gradle clean

